title: Off The Ground Blog
logo: /blog/images/otg-logo.png
description: Off The Ground is a mobile growth consultancy that helps developers of all sizes define and execute their growth strategy. We specialise in running UA campaigns at scale and improving your apps via data-informed optimisations to maximise profitability.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://offtheground.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Xavier Ros√©e
  image: '/images/01.jpg'

# Contact links
# Example of adding a new link to the footer - {name: "Github", icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
- {name: "Email", icon: "ion-ios-mail", link: "mailto:contac@offtheground.io"}

# Slider Section
slider: Life # NOTE - By default, the slider is set to display tags. Now the slider shows the tag with the text "Life". If you do not want to use the slider, leave the slider field empty.

# Comment Section (Disqus)
disqus-identifier: xavierosee # add your shortname for Disqus Comment. For example mr-brown

# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: https://www.instagram.com
userID: 6716400487
accessToken: 6716400487.1677ed0.4fae51c47bc544a895b81756a7d0c477

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed